set quiet

container_runtime := `command -v docker || command -v podman || echo docker`

default:
    just --list

local_service_up:
    {{container_runtime}} compose up -d

test:
    go test

lint:
    go vet

[no-quiet]
fmt:
    test -z $(gofmt -l .) || gofmt -l . | false
    test -z $(goimports -l .) || goimports -l . | false

[no-quiet]
fmt_fix:
    gofmt -s -w .
    goimports -w .

