set quiet

default:
    just --list

start_local_mongo:
    docker run --name edgy-mongo -d -p 27017:27017 mongo:8.2.2-noble

start_local_cdn:
    docker run --name edgy-cdn -d -p 8080:80 nginx:1.29.3-alpine

build:
    go build

run: build
    ./edgy

test:
    go test

lint:
    go vet

[no-quiet]
fmt:
	test -z $(gofmt -l .) || gofmt -l . | false

[no-quiet]
fmt_fix:
	gofmt -s -w .

